################### Experiment information ######################
description: ProstateProtoViT model
run_name: "ProstateProtoViT_moreepochs"
wandb_mode: 'online'
abstain_class: True
base_dir: /home/obed/scratchs
seed: 42

architecture:
  base_architecture: "deit_small_patch16_224"
  radius: 1 # unit of patches 
  img_size: 224
  deit_small_patch16_224:
    prototype_shape: [50, 384, 4]
  deit_tiny_patch16_224:
    prototype_shape: [50, 192, 4]
  cait_xxs24_224:
    prototype_shape: [50, 192, 4]

train:
  dropout_rate: 0.0
  num_classes: 5
  prototype_activation_function: 'log'
  add_on_layers_type: 'regular'
  experiment_run: 'exp1'
  model_dir: ${base_dir}/saved_models/${architecture.base_architecture}/${train.experiment_run}/
  joint_optimizer_lrs: {"features": 5e-5, "prototype_vectors": 3e-3} #2e-5,#1e-4,#1e-5
  joint_lr_step_size: 5
  stage_2_lrs: {'patch_select':5e-5}
  warm_optimizer_lrs: {'features': 1e-7,'prototype_vectors': 3e-3}
  last_layer_optimizer_lr: 1e-4
  coefs: {
    'crs_ent': 1,
    'clst': -0.8,
    'sep': 0.1,
    'l1': 1e-2,
    'orth': 1e-3,
    'coh': 3e-3,
  }
  coefs_slots: {'coh': 1e-6}
  sum_cls: False
  k: 1
  sig_temp: 100
  num_joint_epochs: 40
  num_warm_epochs: 10
  num_finetune_epochs: 15
  slots_train_epoch: 5
  push_start: 10

data:
  fold: 0
  n_folds: 5
  test_center: null
  exclude_benign_cores_from_positive_patients: true
  involvement_threshold_pct: null
  undersample_benign_ratio: null
  cohort_selection_mode: splits_file
  splits_file: "/datasets/exactvu_pca/OPTIMUM/processed/processed/UA_annotated_needles/splits.json"
  dataset: default
  batch_size: 128
  num_workers: 16
  train_subsample_seed: 42
  augmentations: random_crop
  image_size: ${architecture.img_size}
  first_downsample_size: null
  mask_size: ${architecture.img_size}
  limit_train_data: null
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  flip_ud: false
  frames: first
  crop_to_prostate: True
  rf_as_bmode: false
  include_rf: false
  return_raw_images: False
  data_path: "/datasets/exactvu_pca/OPTIMUM/UA_OL_PU_annotated_needles_multiframe"

wandb:
  name: ${run_name}_fold${data.fold}
  project: prostate_prototypes