################### Experiment information ######################
description: ProstateProtoViT model
run_name: "ProstateProtoViT_dino_newsplit"
wandb_mode: 'online'
abstain_class: True
base_dir: /scratch/obed
seed: 42
fold: 0

architecture:
  base_architecture: "dinov3" #"deit_small_patch16_224"
  radius: 1 # unit of patches 
  img_size: 224
  deit_small_patch16_224:
    prototype_shape: [15, 384, 4]
  deit_tiny_patch16_224:
    prototype_shape: [50, 192, 4]
  cait_xxs24_224:
    prototype_shape: [50, 192, 4]
  dinov3:
    prototype_shape: [50, 1024, 4]
    # prototype_shape: [100, 4096, 4]


train:
  dropout_rate: 0.3
  num_classes: 5
  prototype_activation_function: 'log' #'log'
  add_on_layers_type: 'regular'
  experiment_run: ${run_name}
  model_dir: ${base_dir}/saved_models/${architecture.base_architecture}/${train.experiment_run}/${fold}
  joint_optimizer_lrs: {"features": 5e-6, "prototype_vectors": 3e-3} #5e-5 #2e-5,#1e-4,#1e-5 #5e-6 #5e-4
  joint_lr_step_size: 100 #virtually disabling it so that I use a const lr
  stage_2_lrs: {'patch_select':5e-5}
  warm_optimizer_lrs: {'features': 5e-6,'prototype_vectors': 3e-3} #1e-7 #5e-5 1e-3
  last_layer_optimizer_lr: 1e-4 #1e-4
  coefs: {
    'crs_ent': 1,
    'clst': -0.8,
    'sep': 0.5, #0.1 #0.5
    'l1': 1e-3, #1e-5, #1e-2,
    'orth': 1e-3, #1e-3 #5e-2
    'coh': 3e-3,
  }
  coefs_slots: {'coh': 1e-6}
  sum_cls: False
  k: 1
  sig_temp: 100
  num_joint_epochs: 90
  num_warm_epochs: 5
  num_finetune_epochs: 15
  slots_train_epoch: 10
  push_start: 10
  layers: null #[4,11,17,23]

data:
  fold: ${fold}
  n_folds: 5
  test_center: null
  exclude_benign_cores_from_positive_patients: true
  involvement_threshold_pct: null
  undersample_benign_ratio: null
  cohort_selection_mode: splits_file
  splits_file: "/home/obed/projects/aip-medilab/obed/medproj/ProstoViT/kfold_primus_splits.json" #"/datasets/exactvu_pca/OPTIMUM/processed/processed/UA_annotated_needles/splits.json"
  dataset: default
  batch_size: 64
  num_workers: 16
  train_subsample_seed: 42
  augmentations: "all"
  augment_strength: "strong"  # or "light" / "strong"
  image_size: ${architecture.img_size}
  first_downsample_size: null
  mask_size: ${architecture.img_size}
  limit_train_data: null
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  flip_ud: false
  frames: first
  crop_to_prostate: True
  rf_as_bmode: false
  include_rf: false
  return_raw_images: False
  data_path: "/datasets/exactvu_pca/OPTIMUM/UA_OL_PU_annotated_needles_multiframe"

wandb:
  name: ${run_name}_fold${data.fold}
  project: prostate_prototypes